<?php

function character_attributes_form_alter(&$form, &$form_state, $form_id, $node) {
    // find form id on target page
    // print_r($form_id);
    if ($form_id == 'fifth_cleric_character_node_form') {
        // print entire form so that you can find a specific value
        // print '<pre>';
        // print_r($form);
        // print '</pre>';
        
        $number_of_attributes = 6;
        $attribute = array();
        $modifiers = array();

        while ($number_of_attributes > 0) {
            $number_of_attributes--;
        
            $dice_array = array();
            $number_of_dice = 4;
            $dice_min = 1;
            $dice_max = 6;
            
            while ($number_of_dice > 0) {
                $number_of_dice--;
                array_push($dice_array, (rand($dice_min, $dice_max)));
            }
            
            sort ($dice_array, SORT_NUMERIC);
            array_shift($dice_array);
            $dice_roll_total = array_sum($dice_array);
            array_push($attribute, $dice_roll_total);
        }   
        
        sort ($attribute, SORT_NUMERIC);
            
        //for clerics only
        $wis = $attribute[5];
        $dex = $attribute[4];
        $con = $attribute[3];
        $str = $attribute[2];
        $cha = $attribute[1];
        $int = $attribute[0];
        
        // $items = field_get_items('node', $node, 'field_race');
        // $item = array_shift($items);
        // $race = $item[0]['value'];
        
        // $race = $form['field_fifth_constitution']['und'];
        // print '<pre>';
        // print_r($race);
        // print '</pre>';

        
        //translates attributes to modifiers
        foreach ($attribute as $stat) {
            if ($stat == 3) {
                array_push($modifiers, -4);
            } elseif ($stat == 4 || $stat == 5) {
                array_push($modifiers, -3);
            } elseif ($stat == 6 || $stat == 7) {
                array_push($modifiers, -2);
            } elseif ($stat == 8 || $stat == 9) {
                array_push($modifiers, -1);
            } elseif ($stat == 10 || $stat == 11) {
                array_push($modifiers, 0);
            } elseif ($stat == 12 || $stat == 13) {
                array_push($modifiers, 1);
            } elseif ($stat == 14 || $stat == 15) {
                array_push($modifiers, 2);
            } elseif ($stat == 16 || $stat == 17) {
                array_push($modifiers, 3);
            } else {
                array_push($modifiers, 4);
            }
        }
        
        sort ($modifiers, SORT_NUMERIC);

        $wismod = $modifiers[5];
        $dexmod = $modifiers[4];
        $conmod = $modifiers[3];
        $strmod = $modifiers[2];
        $chamod = $modifiers[1];
        $intmod = $modifiers[0];
        

        //hiding class field because it is needed for conditional field logic, but not needed for interface
        $form['field_fifth_class']['und']['#prefix'] = "<div style='display: none'>";
        $form['field_fifth_class']['und']['#suffix'] = "</div>";
        
        //setting default attribute values
        $form['field_fifth_strength']['und']['0']['value']['#default_value'] = $str;
        $form['field_fifth_dexterity']['und']['0']['value']['#default_value'] = $dex;
        $form['field_fifth_constitution']['und']['0']['value']['#default_value'] = $con;
        $form['field_fifth_intelligence']['und']['0']['value']['#default_value'] = $int;
        $form['field_fifth_wisdom']['und']['0']['value']['#default_value'] = $wis;
        $form['field_fifth_charisma']['und']['0']['value']['#default_value'] = $cha;
        
        $form['field_fifth_strength_modifier']['und']['0']['value']['#default_value'] = $strmod;
        $form['field_fifth_dexterity_modifier']['und']['0']['value']['#default_value'] = $dexmod;
        $form['field_fifth_constitution_modifie']['und']['0']['value']['#default_value'] = $conmod;
        $form['field_fifth_intelligence_modifie']['und']['0']['value']['#default_value'] = $intmod;
        $form['field_fifth_wisdom_modifier']['und']['0']['value']['#default_value'] = $wismod;
        $form['field_fifth_charisma_modifier']['und']['0']['value']['#default_value'] = $chamod;
        
        //setting default skill/initiative values
        $form['field_fifth_athletics']['und']['0']['value']['#default_value'] = $strmod;
        $form['field_fifth_initiative']['und']['0']['value']['#default_value'] =
        $form['field_fifth_acrobatics']['und']['0']['value']['#default_value'] =
        $form['field_fifth_sleight_of_hand']['und']['0']['value']['#default_value'] =
        $form['field_fifth_stealth']['und']['0']['value']['#default_value'] = $dexmod;
        $form['field_fifth_arcana']['und']['0']['value']['#default_value'] =
        $form['field_fifth_history']['und']['0']['value']['#default_value'] =
        $form['field_fifth_investigation']['und']['0']['value']['#default_value'] =
        $form['field_fifth_nature']['und']['0']['value']['#default_value'] =
        $form['field_fifth_religion']['und']['0']['value']['#default_value'] = $intmod;
        $form['field_fifth_animal_handling']['und']['0']['value']['#default_value'] =
        $form['field_fifth_insight']['und']['0']['value']['#default_value'] =
        $form['field_fifth_medicine']['und']['0']['value']['#default_value'] =
        $form['field_fifth_perception']['und']['0']['value']['#default_value'] =
        $form['field_fifth_survival']['und']['0']['value']['#default_value'] = $wismod;
        $form['field_fifth_deception']['und']['0']['value']['#default_value'] =
        $form['field_fifth_intimidation']['und']['0']['value']['#default_value'] =
        $form['field_fifth_performance']['und']['0']['value']['#default_value'] =
        $form['field_fifth_persuasion']['und']['0']['value']['#default_value'] = $chamod;
        
        //setting default proficiency values
        $form['field_fifth_armor_proficiency']['und']['0']['value']['#default_value'] = "Light, Medium, Shields";
        $form['field_fifth_weapon_proficiency']['und']['0']['value']['#default_value'] = "All simple";
        
        //class features
        $cleric_features = array();
        $cleric_features[] = "Spellcasting.
As a conduit for divine power, you can cast cleric spells.";
        $cleric_features[] = "Cantrips.
At 1st level, you know three cantrips of your choice from the cleric spell list.";
        $cleric_features[] = "Preparing and Casting Spells.
To cast one of these spells, you must expend a slot of the spell’s level or higher. You regain all expended spell slots when you finish a long rest.
You prepare the list of cleric spells that are available for you to cast, choosing from the cleric spell list. When you do so, choose a number of cleric spells equal to your Wisdom modifier + your cleric level (minimum of one spell). The spells must be of a level for which you have spell slots.
You can change your list of prepared spells when you finish a long rest. Preparing a new list of cleric spells requires time spent in prayer and meditation: at least 1 minute per spell level for each spell on your list.";
        $cleric_features[] = "Spellcasting Ability.
Wisdom is your spellcasting ability for your cleric spells. The power of your spells comes from your devotion to your deity. You use your Wisdom whenever a cleric spell refers to your spellcasting ability. In addition, you use your Wisdom modifier when setting the saving throw DC for a cleric spell you cast and when making an attack roll with one.";
        $cleric_features[] = "Ritual Casting.
You can cast a cleric spell as a ritual if that spell has the ritual tag and you have the spell prepared.";
        $cleric_features[] = "Spellcasting Focus.
You can use a holy symbol as a spellcasting focus for your cleric spells.";
        $cleric_features[] = "Divine Domain.
Choose one domain related to your deity: Knowledge, Life, Light, Nature, Tempest, Trickery, or War.
Your choice grants you domain spells and other features when you choose it at 1st level. It also grants you additional ways to use Channel Divinity when you gain that feature at 2nd level, and additional benefits at 6th, 8th, and 17th levels.";
        $cleric_features[] = "Domain Spells.
Each domain has a list of spells—its domain spells—that you gain at the cleric levels noted in the domain description. Once you gain a domain spell, you always have it prepared, and it doesn’t count against the number of spells you can prepare each day.
If you have a domain spell that doesn’t appear on the cleric spell list, the spell is nonetheless a cleric spell for you.";

        //setting cleric features default values
        $i = 0;
        while($i<count($cleric_features)) {
            $form['field_fifth_class_features']['und'][$i]['value']['#default_value'] = $cleric_features[$i];
            $i++;
        }
        
        //adding AJAX to check race and add bonuses accordingly
        //this is the part being refreshed
        //race-check prefix ids
        $form['field_fifth_constitution']['und']['#prefix'] = '<div id="race-check-con">';
        $form['field_fifth_speed']['und']['#prefix'] = '<div id="race-check-speed">';
        $form['field_fifth_racial_features']['und']['#prefix'] = '<div id="race-check-features">';
        $form['field_fifth_constitution_modifie']['und']['#prefix'] = '<div id="race-check-conmod">';
        $form['field_fifth_hit_dice']['und']['#prefix'] = '<div id="race-check-hit-dice">';
        $form['field_fifth_weapon_proficiency']['und']['#prefix'] = '<div id="race-check-weapon-proficiency">';
        $form['field_fifth_languages']['und']['#prefix'] = '<div id="race-check-language">';
        //subrace-check prefix ids
        $form['field_fifth_wisdom']['und']['#prefix'] = '<div id="subrace-check-wis">';
        $form['field_fifth_subracial_features']['und']['#prefix'] = '<div id="subrace-check-features">';
        $form['field_fifth_hit_points']['und']['#prefix'] = '<div id="subrace-check-hp">';
        $form['field_fifth_strength']['und']['#prefix'] = '<div id="subrace-check-strength">';
        //domain-check prefix ids
        $form['field_fifth_domain_features']['und']['#prefix'] = '<div id="domain-check-features">';
        //background-check prefix ids
        $form['field_fifth_background_feature']['und']['#prefix'] = '<div id="background-check-feature">';
        $form['field_fifth_background_skills']['und']['#prefix'] = '<div id="background-check-skills">';
        $form['field_fifth_background_tool_prof']['und']['#prefix'] = '<div id="background-check-tool-proficiency">';

        //suffixes
        $form['field_fifth_constitution']['und']['#suffix'] = 
        $form['field_fifth_speed']['und']['#suffix'] = 
        $form['field_fifth_racial_features']['und']['#suffix'] = 
        $form['field_fifth_constitution_modifie']['und']['#suffix'] = 
        $form['field_fifth_hit_dice']['und']['#suffix'] = 
        $form['field_fifth_wisdom']['und']['#suffix'] = 
        $form['field_fifth_hit_points']['und']['#suffix'] = 
        $form['field_fifth_subracial_features']['und']['#suffix'] = 
        $form['field_fifth_weapon_proficiency']['und']['#suffix'] = 
        $form['field_fifth_languages']['und']['#suffix'] = 
        $form['field_fifth_strength']['und']['#suffix'] =
        $form['field_fifth_domain_features']['und']['#suffix'] =
        $form['field_fifth_background_feature']['und']['#suffix'] = 
        $form['field_fifth_background_skills']['und']['#suffix'] =
        $form['field_fifth_background_tool_prof']['und']['#suffix'] = 
            '</div>';
        
        
        //racial features
        //dwarven
        $dwarven_features = array();
        $dwarven_features[] = "Age. 
Dwarves mature at the same rate as humans, but they’re considered young until they reach the age of 50. On average, they live about 350 years.";
        $dwarven_features[] = "Alignment. 
Most dwarves are lawful, believing firmly in the benefits of a well-ordered society. They tend toward good as well, with a strong sense of fair play and a belief that everyone deserves to share in the benefits of a just order.";
        $dwarven_features[] = "Size. 
Dwarves stand between 4 and 5 feet tall and average about 150 pounds. Your size is Medium.";
        $dwarven_features[] = "Darkvision. 
Accustomed to life underground, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.";
        $dwarven_features[] = "Dwarven Resilience. 
You have advantage on saving throws against poison, and you have resistance against poison damage.";
        $dwarven_features[] = "Stonecunning. 
Whenever you make an Intelligence (History) check related to the origin of stonework, you are considered proficient in the History skill and add double your proficiency bonus to the check, instead of your normal proficiency bonus.";

        //domain features
        //knowledge
        $knowledge_features = array();
        $knowledge_features[] = "Blessings of Knowledge.
At 1st level, you learn two languages of your choice.";
        $knowledge_features[] = "Blessings of Knowledge.
You also become proficient in your choice of two of the following skills: Arcana, History, Nature, or Religion. Your proficiency bonus is doubled for any ability check you make that uses either of those skills.";

        //background features
        //acolyte
        $acolyte_features = array();
        $acolyte_features[] = "Shelter of the Faithful.
As an acolyte, you command the respect of those who share your faith, and you can perform the religious ceremonies of your deity. You and your adventuring companions can expect to receive free healing and care at a temple, shrine, or other established presence of your faith, though you must provide any material components needed for spells. Those who share your religion will support you (but only you) at a modest lifestyle.
You might also have ties to a specific temple dedicated to your chosen deity or pantheon, and you have a residence there. This could be the temple where you used to serve, if you remain on good terms with it, or a temple where you have found a new home. While near your temple, you can call upon the priests for assistance, provided the assistance you ask for is not hazardous and you remain in good standing with your temple.";
        //charlatan
        $charlatan_features = array();
        $charlatan_features[] = "False Identity.
You have created a second identity that includes documentation, established acquaintances, and disguises that allow you to assume that persona. Additionally, you can forge documents including official papers and personal letters, as long as you have seen an example of the kind of document or the handwriting you are trying to copy.";

        //triggers the replacement
        //race
        $form['field_race']['und']['#ajax'] = array(
            'callback' => 'character_attributes_race_ajax_callback',
            'wrapper' => 'race-check',
        );
        //dwarven subrace
        $form['field_fifth_dwarven_sub_race']['und']['#ajax'] = array(
            'callback' => 'character_attributes_dwarven_subrace_ajax_callback',
            'wrapper' => 'subrace-check',
        );
        //cleric domain
        $form['field_fifth_cleric_domain']['und']['#ajax'] = array(
            'callback' => 'character_attributes_domain_ajax_callback',
            'wrapper' => 'domain-check',
        );
        //background
        $form['field_fifth_backgrounds']['und']['#ajax'] = array(
            'callback' => 'character_attributes_background_ajax_callback',
            'wrapper' => 'background-check',
        );


        // print '<pre>';
        // print_r($form);
        // print '</pre>';
        
        //logic for AJAX call
        //Dwarven logics
        $current_conmod = isset($form_state['input']['field_fifth_constitution_modifie']['und'][0]['value']) ? $form_state['input']['field_fifth_constitution_modifie']['und'][0]['value'] : "";
        if(!empty($form_state['values']['field_race'])) {
            if ($form_state['values']['field_race']['und'][0]['value'] == '1') {
                $current_con = $form_state['input']['field_fifth_constitution']['und'][0]['value'];
                unset($form_state['input']['field_fifth_constitution']['und'][0]['value']);
                $form['field_fifth_constitution']['und'][0]['value']['#default_value'] = 2+$current_con;
                $form['field_fifth_constitution_modifie']['und'][0]['value']['#default_value'] = $current_conmod + 1;
                unset($form_state['input']['field_fifth_speed']['und'][0]['value']);
                $form['field_fifth_speed']['und'][0]['value']['#default_value'] = 25;
                unset($form_state['input']['field_fifth_racial_features']['und'][0]['value']);
                $i = 0;
                while($i<count($dwarven_features)) {
                    unset($form_state['input']['field_fifth_racial_features']['und'][$i]['value']);
                    $form['field_fifth_racial_features']['und'][$i]['value']['#default_value'] = $dwarven_features[$i];
                    $i++;
                }
                unset($form_state['input']['field_fifth_hit_dice']['und'][0]['value']);
                $form['field_fifth_hit_dice']['und'][0]['value']['#default_value'] = '1d8';
                unset($form_state['input']['field_fifth_weapon_proficiency']['und'][0]['value']);
                $form['field_fifth_weapon_proficiency']['und'][0]['value']['#default_value'] = 'All simple, Battleaxe, Warhammer';
                unset($form_state['input']['field_fifth_languages']['und'][0]['value']);
                $form['field_fifth_languages']['und'][0]['value']['#default_value'] = 'Common, Dwarven';
            } 
        }
        //hill dwarf logics
        if(!empty($form_state['values']['field_fifth_dwarven_sub_race'])) {
            if ($form_state['values']['field_fifth_dwarven_sub_race']['und'][0]['value'] == '1') {
                $current_wis = $form_state['input']['field_fifth_wisdom']['und'][0]['value'];
                unset($form_state['input']['field_fifth_wisdom']['und'][0]['value']);
                $form['field_fifth_wisdom']['und'][0]['value']['#default_value'] = 1 + $current_wis;
                unset($form_state['input']['field_fifth_subracial_features']['und'][0]['value']);
                $form['field_fifth_subracial_features']['und'][0]['value']['#default_value'] = "Dwarven Toughness. Your hit point maximum increases by 1, and it increases by 1 every time you gain a level.";
                unset($form_state['input']['field_fifth_hit_points']['und'][0]['value']);
                $form['field_fifth_hit_points']['und'][0]['value']['#default_value'] = $current_conmod + 9;
            }
        }
        //mountain dwarf logics
        if(!empty($form_state['values']['field_fifth_dwarven_sub_race'])) {
            if ($form_state['values']['field_fifth_dwarven_sub_race']['und'][0]['value'] == '2') {
                $current_str = $form_state['input']['field_fifth_strength']['und'][0]['value'];
                unset($form_state['input']['field_fifth_strength']['und'][0]['value']);
                $form['field_fifth_strength']['und'][0]['value']['#default_value'] = 2 + $current_str;
                unset($form_state['input']['field_fifth_hit_points']['und'][0]['value']);
                $form['field_fifth_hit_points']['und'][0]['value']['#default_value'] = $current_conmod + 8;
            }
        }
        //knowledge domain logics
        if(!empty($form_state['values']['field_fifth_cleric_domain'])) {
            if ($form_state['values']['field_fifth_cleric_domain']['und'][0]['value'] == 'Knowledge') {
                $i = 0;
                while($i<count($knowledge_features)) {
                    unset($form_state['input']['field_fifth_domain_features']['und'][$i]['value']);
                    $form['field_fifth_domain_features']['und'][$i]['value']['#default_value'] = $knowledge_features[$i];
                    $i++;
                }
            }
        }
        //background logics
        if(!empty($form_state['values']['field_fifth_backgrounds'])) {
            //acolyte background logics
            if ($form_state['values']['field_fifth_backgrounds']['und'][0]['value'] == '1') {
                $i = 0;
                while($i<count($acolyte_features)) {
                    unset($form_state['input']['field_fifth_background_feature']['und'][$i]['value']);
                    $form['field_fifth_background_feature']['und'][$i]['value']['#default_value'] = $acolyte_features[$i];
                    $i++;
                }
                unset($form_state['input']['field_fifth_background_skills']['und'][0]['value']);
                $form['field_fifth_background_skills']['und'][0]['value']['#default_value'] = 'Insight, Religion';
            }
            //charlatan background logics
            if ($form_state['values']['field_fifth_backgrounds']['und'][0]['value'] == '2') {
                $i = 0;
                while($i<count($charlatan_features)) {
                    unset($form_state['input']['field_fifth_background_feature']['und'][$i]['value']);
                    $form['field_fifth_background_feature']['und'][$i]['value']['#default_value'] = $charlatan_features[$i];
                    $i++;
                }
                unset($form_state['input']['field_fifth_background_skills']['und'][0]['value']);
                $form['field_fifth_background_skills']['und'][0]['value']['#default_value'] = 'Deception, Sleight of Hand';
                unset($form_state['input']['field_fifth_background_tool_prof']['und'][0]['value']);
                $form['field_fifth_background_tool_prof']['und'][0]['value']['#default_value'] = 'Disguise kit, Forgery kit';
            }
        }
    }   
}

// AJAX callback function
function character_attributes_race_ajax_callback($form, $form_state) {
    $commands = array();
    $commands[] = ajax_command_replace('#race-check-con', drupal_render($form['field_fifth_constitution']));
    $commands[] = ajax_command_replace('#race-check-speed', drupal_render($form['field_fifth_speed']));
    $commands[] = ajax_command_replace('#race-check-features', drupal_render($form['field_fifth_racial_features']));
    $commands[] = ajax_command_replace('#race-check-conmod', drupal_render($form['field_fifth_constitution_modifie']));
    $commands[] = ajax_command_replace('#race-check-hit-dice', drupal_render($form['field_fifth_hit_dice']));
    $commands[] = ajax_command_replace('#race-check-weapon-proficiency', drupal_render($form['field_fifth_weapon_proficiency']));
    $commands[] = ajax_command_replace('#race-check-language', drupal_render($form['field_fifth_languages']));
    return array('#type' => 'ajax', '#commands' => $commands);
}

function character_attributes_dwarven_subrace_ajax_callback($form, $form_state) {
    $commands = array();
    $commands[] = ajax_command_replace('#subrace-check-wis', drupal_render($form['field_fifth_wisdom']));
    $commands[] = ajax_command_replace('#subrace-check-features', drupal_render($form['field_fifth_subracial_features']));
    $commands[] = ajax_command_replace('#subrace-check-hp', drupal_render($form['field_fifth_hit_points']));
    $commands[] = ajax_command_replace('#subrace-check-strength', drupal_render($form['field_fifth_strength']));
    return array('#type' => 'ajax', '#commands' => $commands);
}

function character_attributes_domain_ajax_callback($form, $form_state) {
    $commands = array();
    $commands[] = ajax_command_replace('#domain-check-features', drupal_render($form['field_fifth_domain_features']));
    return array('#type' => 'ajax', '#commands' => $commands);
}

function character_attributes_background_ajax_callback($form, $form_state) {
    $commands = array();
    $commands[] = ajax_command_replace('#background-check-feature', drupal_render($form['field_fifth_background_feature']));
    $commands[] = ajax_command_replace('#background-check-skills', drupal_render($form['field_fifth_background_skills']));
    $commands[] = ajax_command_replace('#background-check-tool-proficiency', drupal_render($form['field_fifth_background_tool_prof']));
    return array('#type' => 'ajax', '#commands' => $commands);
}
