<?php

function character_attributes_form_alter(&$form, &$form_state, $form_id, $node) {
    // find form id on target page
    // print_r($form_id);
    if ($form_id == 'fifth_cleric_character_node_form') {
        // print entire form so that you can find a specific value
        // print '<pre>';
        // print_r($form);
        // print '</pre>';
        
        $number_of_attributes = 6;
        $attribute = array();
        $modifiers = array();

        while ($number_of_attributes > 0) {
            $number_of_attributes--;
        
            $dice_array = array();
            $number_of_dice = 4;
            $dice_min = 1;
            $dice_max = 6;
            
            while ($number_of_dice > 0) {
                $number_of_dice--;
                array_push($dice_array, (rand($dice_min, $dice_max)));
            }
            
            sort ($dice_array, SORT_NUMERIC);
            array_shift($dice_array);
            $dice_roll_total = array_sum($dice_array);
            array_push($attribute, $dice_roll_total);
        }   
        
        sort ($attribute, SORT_NUMERIC);
            
        //for clerics only
        $wis = $attribute[5];
        $dex = $attribute[4];
        $con = $attribute[3];
        $str = $attribute[2];
        $cha = $attribute[1];
        $int = $attribute[0];
        
        // $items = field_get_items('node', $node, 'field_race');
        // $item = array_shift($items);
        // $race = $item[0]['value'];
        
        // $race = $form['field_fifth_constitution']['und'];
        // print '<pre>';
        // print_r($race);
        // print '</pre>';

        
        //translates attributes to modifiers
        foreach ($attribute as $stat) {
            if ($stat == 3) {
                array_push($modifiers, -4);
            } elseif ($stat == 4 || $stat == 5) {
                array_push($modifiers, -3);
            } elseif ($stat == 6 || $stat == 7) {
                array_push($modifiers, -2);
            } elseif ($stat == 8 || $stat == 9) {
                array_push($modifiers, -1);
            } elseif ($stat == 10 || $stat == 11) {
                array_push($modifiers, 0);
            } elseif ($stat == 12 || $stat == 13) {
                array_push($modifiers, 1);
            } elseif ($stat == 14 || $stat == 15) {
                array_push($modifiers, 2);
            } elseif ($stat == 16 || $stat == 17) {
                array_push($modifiers, 3);
            } else {
                array_push($modifiers, 4);
            }
        }
        
        sort ($modifiers, SORT_NUMERIC);

        $wismod = $modifiers[5];
        $dexmod = $modifiers[4];
        $conmod = $modifiers[3];
        $strmod = $modifiers[2];
        $chamod = $modifiers[1];
        $intmod = $modifiers[0];
        

        //hiding class field because it is needed for conditional field logic, but not needed for interface
        $form['field_fifth_class']['und']['#prefix'] = "<div style='display: none'>";
        $form['field_fifth_class']['und']['#suffix'] = "</div>";
        
        //setting default attribute values
        $form['field_fifth_strength']['und']['0']['value']['#default_value'] = $str;
        $form['field_fifth_dexterity']['und']['0']['value']['#default_value'] = $dex;
        $form['field_fifth_constitution']['und']['0']['value']['#default_value'] = $con;
        $form['field_fifth_intelligence']['und']['0']['value']['#default_value'] = $int;
        $form['field_fifth_wisdom']['und']['0']['value']['#default_value'] = $wis;
        $form['field_fifth_charisma']['und']['0']['value']['#default_value'] = $cha;
        
        $form['field_fifth_strength_modifier']['und']['0']['value']['#default_value'] = $strmod;
        $form['field_fifth_dexterity_modifier']['und']['0']['value']['#default_value'] = $dexmod;
        $form['field_fifth_constitution_modifie']['und']['0']['value']['#default_value'] = $conmod;
        $form['field_fifth_intelligence_modifie']['und']['0']['value']['#default_value'] = $intmod;
        $form['field_fifth_wisdom_modifier']['und']['0']['value']['#default_value'] = $wismod;
        $form['field_fifth_charisma_modifier']['und']['0']['value']['#default_value'] = $chamod;
        
        //setting default proficiency values
        $form['field_fifth_hit_dice']['und'][0]['value']['#default_value'] = '1d8';
        $form['field_fifth_armor_proficiency']['und']['0']['value']['#default_value'] = "Light, Medium, Shields";
        $form['field_fifth_weapon_proficiency']['und']['0']['value']['#default_value'] = "All simple";
        
        //class features
        $cleric_features = array();
        $cleric_features[] = "Spellcasting.
As a conduit for divine power, you can cast cleric spells.";
        $cleric_features[] = "Cantrips.
At 1st level, you know three cantrips of your choice from the cleric spell list.";
        $cleric_features[] = "Preparing and Casting Spells.
To cast one of these spells, you must expend a slot of the spell’s level or higher. You regain all expended spell slots when you finish a long rest.
You prepare the list of cleric spells that are available for you to cast, choosing from the cleric spell list. When you do so, choose a number of cleric spells equal to your Wisdom modifier + your cleric level (minimum of one spell). The spells must be of a level for which you have spell slots.
You can change your list of prepared spells when you finish a long rest. Preparing a new list of cleric spells requires time spent in prayer and meditation: at least 1 minute per spell level for each spell on your list.";
        $cleric_features[] = "Spellcasting Ability.
Wisdom is your spellcasting ability for your cleric spells. The power of your spells comes from your devotion to your deity. You use your Wisdom whenever a cleric spell refers to your spellcasting ability. In addition, you use your Wisdom modifier when setting the saving throw DC for a cleric spell you cast and when making an attack roll with one.";
        $cleric_features[] = "Ritual Casting.
You can cast a cleric spell as a ritual if that spell has the ritual tag and you have the spell prepared.";
        $cleric_features[] = "Spellcasting Focus.
You can use a holy symbol as a spellcasting focus for your cleric spells.";
        $cleric_features[] = "Divine Domain.
Choose one domain related to your deity: Knowledge, Life, Light, Nature, Tempest, Trickery, or War.
Your choice grants you domain spells and other features when you choose it at 1st level. It also grants you additional ways to use Channel Divinity when you gain that feature at 2nd level, and additional benefits at 6th, 8th, and 17th levels.";
        $cleric_features[] = "Domain Spells.
Each domain has a list of spells—its domain spells—that you gain at the cleric levels noted in the domain description. Once you gain a domain spell, you always have it prepared, and it doesn’t count against the number of spells you can prepare each day.
If you have a domain spell that doesn’t appear on the cleric spell list, the spell is nonetheless a cleric spell for you.";

        //setting cleric features default values
        $i = 0;
        while($i<count($cleric_features)) {
            $form['field_fifth_class_features']['und'][$i]['value']['#default_value'] = $cleric_features[$i];
            $i++;
        }
        
        //adding AJAX to check race and add bonuses accordingly
        //this is the part being refreshed
        //race-check prefix ids
        $form['field_fifth_constitution']['und']['#prefix'] = '<div id="race-check-con">';
        $form['field_fifth_speed']['und']['#prefix'] = '<div id="race-check-speed">';
        $form['field_fifth_racial_features']['und']['#prefix'] = '<div id="race-check-features">';
        $form['field_fifth_constitution_modifie']['und']['#prefix'] = '<div id="race-check-conmod">';
        $form['field_fifth_hit_dice']['und']['#prefix'] = '<div id="race-check-hit-dice">';
        $form['field_fifth_weapon_proficiency']['und']['#prefix'] = '<div id="race-check-weapon-proficiency">';
        $form['field_fifth_languages']['und']['#prefix'] = '<div id="race-check-language">';
        $form['field_fifth_dexterity']['und']['#prefix'] = '<div id="race-check-dexterity">';
        $form['field_fifth_dexterity_modifier']['und']['#prefix'] = '<div id="race-check-dexmod">';
        $form['field_fifth_racial_skill_prof']['und']['#prefix'] = '<div id="race-check-skill-prof">';
        //subrace-check prefix ids
        //dwarven
        $form['field_fifth_wisdom']['und']['#prefix'] = '<div id="subrace-check-wis">';
        $form['field_fifth_subracial_features']['und']['#prefix'] = '<div id="subrace-check-features">';
        $form['field_fifth_hit_points']['und']['#prefix'] = '<div id="subrace-check-hp">';
        $form['field_fifth_strength']['und']['#prefix'] = '<div id="subrace-check-strength">';
        $form['field_fifth_wisdom_modifier']['und']['#prefix'] = '<div id="subrace-check-wismod">';
        $form['field_fifth_strength_modifier']['und']['#prefix'] = '<div id="subrace-check-strmod">';
        //elven
        $form['field_fifth_intelligence']['und']['#prefix'] = '<div id="subrace-elven-check-int">';
        $form['field_fifth_intelligence_modifie']['und']['#prefix'] = '<div id="subrace-elven-check-intmod">';
        $form['field_fifth_charisma']['und']['#prefix'] = '<div id="subrace-elven-check-cha">';
        $form['field_fifth_charisma_modifier']['und']['#prefix'] = '<div id="subrace-elven-check-chamod">';
        $form['field_fifth_racial_spell']['und']['#prefix'] = '<div id="subrace-elven-check-spell">';
        //domain-check prefix ids
        $form['field_fifth_domain_features']['und']['#prefix'] = '<div id="domain-check-features">';
        $form['field_fifth_armor_proficiency']['und']['#prefix'] = '<div id="domain-check-armor">';
        $form['field_fifth_domain_spells']['und']['#prefix'] = '<div id="domain-check-spells">';
        $form['field_fifth_class_features']['und']['#prefix'] = '<div id="domain-check-class-features">';
        $form['field_fifth_lvl1_spells_prepared']['und']['#prefix'] = '<div id="domain-check-class-spells-level-2">';
        //background-check prefix ids
        $form['field_fifth_background_feature']['und']['#prefix'] = '<div id="background-check-feature">';
        $form['field_fifth_background_skills']['und']['#prefix'] = '<div id="background-check-skills">';
        $form['field_fifth_background_tool_prof']['und']['#prefix'] = '<div id="background-check-tool-proficiency">';
        $form['field_fifth_starting_money']['und']['#prefix'] = '<div id="background-check-money">';
        $form['field_fifth_background_bundle']['und']['#prefix'] = '<div id="background-check-bundle">';
        //skill updates
        //str
        $form['field_fifth_athletics']['und']['#prefix'] = '<div id="skill-check-rewrite-athletics">';
        //dex
        $form['field_fifth_initiative']['und']['#prefix'] = '<div id="skill-check-rewrite-initiative">';
        $form['field_fifth_acrobatics']['und']['#prefix'] = '<div id="skill-check-rewrite-acrobatics">';
        $form['field_fifth_sleight_of_hand']['und']['#prefix'] = '<div id="skill-check-rewrite-sleight-of-hand">';
        $form['field_fifth_stealth']['und']['#prefix'] = '<div id="skill-check-rewrite-stealth">';
        $form['field_fifth_armor_class']['und']['#prefix'] = '<div id="skill-check-rewrite-ac">';
        //int
        $form['field_fifth_arcana']['und']['#prefix'] = '<div id="skill-check-rewrite-arcana">';
        $form['field_fifth_history']['und']['#prefix'] = '<div id="skill-check-rewrite-history">';
        $form['field_fifth_investigation']['und']['#prefix'] = '<div id="skill-check-rewrite-investigation">';
        $form['field_fifth_nature']['und']['#prefix'] = '<div id="skill-check-rewrite-nature">';
        $form['field_fifth_religion']['und']['#prefix'] = '<div id="skill-check-rewrite-religion">'; 
        //wis
        $form['field_fifth_animal_handling']['und']['#prefix'] = '<div id="skill-check-rewrite-animal-handling">';
        $form['field_fifth_insight']['und']['#prefix'] = '<div id="skill-check-rewrite-insight">';
        $form['field_fifth_medicine']['und']['#prefix'] = '<div id="skill-check-rewrite-medicine">';
        $form['field_fifth_perception']['und']['#prefix'] = '<div id="skill-check-rewrite-perception">';
        $form['field_fifth_survival']['und']['#prefix'] = '<div id="skill-check-rewrite-survival">'; 
        //cha
        $form['field_fifth_deception']['und']['#prefix'] = '<div id="skill-check-rewrite-deception">';
        $form['field_fifth_intimidation']['und']['#prefix'] = '<div id="skill-check-rewrite-intimidation">';
        $form['field_fifth_performance']['und']['#prefix'] = '<div id="skill-check-rewrite-performance">';
        $form['field_fifth_persuasion']['und']['#prefix'] = '<div id="skill-check-rewrite-persuasion">'; 
        //skill proficiencies
        $form['field_fifth_arcana_proficiency']['und']['#prefix'] = '<div id="prof-check-arcana">';
        $form['field_fifth_deception_prof']['und']['#prefix'] = '<div id="prof-check-deception">';
        $form['field_fifth_history_proficiency']['und']['#prefix'] = '<div id="prof-check-history">';
        $form['field_fifth_insight_proficiency']['und']['#prefix'] = '<div id="prof-check-insight">';
        $form['field_fifth_medicine_proficiency']['und']['#prefix'] = '<div id="prof-check-medicine">';
        $form['field_fifth_nature_proficiency']['und']['#prefix'] = '<div id="prof-check-nature">';
        $form['field_fifth_perception_prof']['und']['#prefix'] = '<div id="prof-check-perception">';
        $form['field_fifth_persuasion_prof']['und']['#prefix'] = '<div id="prof-check-persuasion">';
        $form['field_fifth_religion_proficiency']['und']['#prefix'] = '<div id="prof-check-religion">';
        $form['field_fifth_sleight_of_hand_prof']['und']['#prefix'] = '<div id="prof-check-sleight-of-hand">';
        
        

        //suffixes
        $form['field_fifth_constitution']['und']['#suffix'] = 
        $form['field_fifth_speed']['und']['#suffix'] = 
        $form['field_fifth_racial_features']['und']['#suffix'] = 
        $form['field_fifth_constitution_modifie']['und']['#suffix'] = 
        $form['field_fifth_hit_dice']['und']['#suffix'] = 
        $form['field_fifth_wisdom']['und']['#suffix'] = 
        $form['field_fifth_hit_points']['und']['#suffix'] = 
        $form['field_fifth_subracial_features']['und']['#suffix'] = 
        $form['field_fifth_weapon_proficiency']['und']['#suffix'] = 
        $form['field_fifth_languages']['und']['#suffix'] = 
        $form['field_fifth_strength']['und']['#suffix'] =
        $form['field_fifth_domain_features']['und']['#suffix'] =
        $form['field_fifth_background_feature']['und']['#suffix'] = 
        $form['field_fifth_background_skills']['und']['#suffix'] =
        $form['field_fifth_background_tool_prof']['und']['#suffix'] = 
        $form['field_fifth_armor_proficiency']['und']['#suffix'] =
        $form['field_fifth_domain_spells']['und']['#suffix'] = 
        $form['field_fifth_dexterity']['und']['#suffix'] = 
        $form['field_fifth_dexterity_modifier']['und']['#suffix'] = 
        $form['field_fifth_racial_skill_prof']['und']['#suffix'] = 
        $form['field_fifth_wisdom_modifier']['und']['#suffix'] =
        $form['field_fifth_intelligence']['und']['#suffix'] =
        $form['field_fifth_intelligence_modifie']['und']['#suffix'] =
        $form['field_fifth_charisma']['und']['#suffix'] = 
        $form['field_fifth_charisma_modifier']['und']['#suffix'] = 
        $form['field_fifth_racial_spell']['und']['#suffix'] =
        $form['field_fifth_athletics']['und']['#suffix'] =
        $form['field_fifth_initiative']['und']['#suffix'] =
        $form['field_fifth_acrobatics']['und']['#suffix'] =
        $form['field_fifth_sleight_of_hand']['und']['#suffix'] =
        $form['field_fifth_stealth']['und']['#suffix'] =
        $form['field_fifth_arcana']['und']['#suffix'] =
        $form['field_fifth_history']['und']['#suffix'] =
        $form['field_fifth_investigation']['und']['#suffix'] =
        $form['field_fifth_nature']['und']['#suffix'] =
        $form['field_fifth_religion']['und']['#suffix'] = 
        $form['field_fifth_animal_handling']['und']['#suffix'] =
        $form['field_fifth_insight']['und']['#suffix'] =
        $form['field_fifth_medicine']['und']['#suffix'] =
        $form['field_fifth_perception']['und']['#suffix'] =
        $form['field_fifth_survival']['und']['#suffix'] = 
        $form['field_fifth_deception']['und']['#suffix'] =
        $form['field_fifth_intimidation']['und']['#suffix'] =
        $form['field_fifth_performance']['und']['#suffix'] =
        $form['field_fifth_persuasion']['und']['#suffix'] = 
        $form['field_fifth_strength_modifier']['und']['#suffix'] =
        $form['field_fifth_arcana_proficiency']['und']['#suffix'] =
        $form['field_fifth_deception_prof']['und']['#suffix'] =
        $form['field_fifth_history_proficiency']['und']['#suffix'] = 
        $form['field_fifth_insight_proficiency']['und']['#suffix'] = 
        $form['field_fifth_medicine_proficiency']['und']['#suffix'] = 
        $form['field_fifth_nature_proficiency']['und']['#suffix'] =
        $form['field_fifth_perception_prof']['und']['#suffix'] =
        $form['field_fifth_persuasion_prof']['und']['#suffix'] = 
        $form['field_fifth_religion_proficiency']['und']['#suffix'] = 
        $form['field_fifth_sleight_of_hand_prof']['und']['#suffix'] =
        $form['field_fifth_starting_money']['und']['#suffix'] =
        $form['field_fifth_background_bundle']['und']['#suffix'] =
        $form['field_fifth_armor_class']['und']['#suffix'] = 
        $form['field_fifth_class_features']['und']['#suffix'] = 
        $form['field_fifth_lvl1_spells_prepared']['und']['#suffix'] =
            '</div>';
        
        //racial features
        //dwarven
        $dwarven_features = array();
        $dwarven_features[] = "Age. 
Dwarves mature at the same rate as humans, but they’re considered young until they reach the age of 50. On average, they live about 350 years.";
        $dwarven_features[] = "Alignment. 
Most dwarves are lawful, believing firmly in the benefits of a well-ordered society. They tend toward good as well, with a strong sense of fair play and a belief that everyone deserves to share in the benefits of a just order.";
        $dwarven_features[] = "Size. 
Dwarves stand between 4 and 5 feet tall and average about 150 pounds. Your size is Medium.";
        $dwarven_features[] = "Darkvision. 
Accustomed to life underground, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.";
        $dwarven_features[] = "Dwarven Resilience. 
You have advantage on saving throws against poison, and you have resistance against poison damage.";
        $dwarven_features[] = "Stonecunning. 
Whenever you make an Intelligence (History) check related to the origin of stonework, you are considered proficient in the History skill and add double your proficiency bonus to the check, instead of your normal proficiency bonus.";
        //elven
        $elven_features = array();
        $elven_features[] = "Age. 
Although elves reach physical maturity at about the same age as humans, the elven understanding of adulthood goes beyond physical growth to encompass worldly experience. An elf typically claims adulthood and an adult name around the age of 100 and can live to be 750 years old.";
        $elven_features[] = "Alignment. 
Elves love freedom, variety, and self expression, so they lean strongly toward the gentler aspects of chaos. They value and protect others' freedom as well as their own, and they are more often good than not. The drow are an exception; their exile into the Underdark has made them vicious and dangerous. Drow are more often evil than not.";
        $elven_features[] = "Size. 
Elves range from under 5 to over 6 feet tall and have slender builds. Your size is Medium.";
        $elven_features[] = "Darkvision. 
Accustomed to twilit forests and the night sky, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.";
        $elven_features[] = "Fey Ancestry. 
You have advantage on saving throws against being charmed, and magic can’t put you to sleep.";
        $elven_features[] = "Trance. 
Elves don’t need to sleep. Instead, they meditate deeply, remaining semiconscious, for 4 hours a day. (The Common word for such meditation is “trance.”) While meditating, you can dream after a fashion; such dreams are actually mental exercises that have become reflexive through years of practice. After resting in this way, you gain the same benefit that a human does from 8 hours of sleep.";
        //elven subclass features
        //drow
        $drow_features = array();
        $drow_features[] = "Superior Darkvision. 
Your darkvision has a radius of 120 feet.";
        $drow_features[] = "Sunlight Sensitivity. 
You have disadvantage on attack rolls and on Wisdom (Perception) checks that rely on sight when you, the target of your attack, or whatever you are trying to perceive is in direct sunlight.";
        $drow_features[] = "Drow Magic. 
When you reach 3rd level, you can cast the faerie fire spell once per day. When you reach 5th level, you can also cast the darkness spell once per day. Charisma is your spellcasting ability for these spells.";

        //domain features
        //knowledge
        $knowledge_features = array();
        $knowledge_features[] = "Blessings of Knowledge.
At 1st level, you learn two languages of your choice.";
        $knowledge_features[] = "Blessings of Knowledge.
You also become proficient in your choice of two of the following skills: Arcana, History, Nature, or Religion. Your proficiency bonus is doubled for any ability check you make that uses either of those skills.";
        $knowledge_spells = array();
        $knowledge_spells[] = "Command (86)";
        $knowledge_spells[] = "Identify (110)";
        //life
        $life_features = array();
        $life_features[] = "Disciple of Life.
Also starting at 1st level, your healing spells are more effective. Whenever you use a spell of 1st level or higher to restore hit points to a creature, the creature regains additional hit points equal to 2 + the spell’s level.";

        //background features
        //acolyte
        $acolyte_features = array();
        $acolyte_features[] = "Shelter of the Faithful.
As an acolyte, you command the respect of those who share your faith, and you can perform the religious ceremonies of your deity. You and your adventuring companions can expect to receive free healing and care at a temple, shrine, or other established presence of your faith, though you must provide any material components needed for spells. Those who share your religion will support you (but only you) at a modest lifestyle.
You might also have ties to a specific temple dedicated to your chosen deity or pantheon, and you have a residence there. This could be the temple where you used to serve, if you remain on good terms with it, or a temple where you have found a new home. While near your temple, you can call upon the priests for assistance, provided the assistance you ask for is not hazardous and you remain in good standing with your temple.";
        //charlatan
        $charlatan_features = array();
        $charlatan_features[] = "False Identity.
You have created a second identity that includes documentation, established acquaintances, and disguises that allow you to assume that persona. Additionally, you can forge documents including official papers and personal letters, as long as you have seen an example of the kind of document or the handwriting you are trying to copy.";

        //triggers the replacement
        //race
        $form['field_race']['und']['#ajax'] = array(
            'callback' => 'character_attributes_race_ajax_callback',
            'wrapper' => 'race-check',
        );
        //dwarven subrace
        $form['field_fifth_dwarven_sub_race']['und']['#ajax'] = array(
            'callback' => 'character_attributes_dwarven_subrace_ajax_callback',
            'wrapper' => 'subrace-check',
        );
        //elven subrace
        $form['field_fifth_elven_sub_race']['und']['#ajax'] = array(
            'callback' => 'character_attributes_elven_subrace_ajax_callback',
            'wrapper' => 'subrace-check-elven',
        );
        //cleric domain
        $form['field_fifth_cleric_domain']['und']['#ajax'] = array(
            'callback' => 'character_attributes_domain_ajax_callback',
            'wrapper' => 'domain-check',
        );
        //background
        $form['field_fifth_backgrounds']['und']['#ajax'] = array(
            'callback' => 'character_attributes_background_ajax_callback',
            'wrapper' => 'background-check',
        );
        //reprocessing skill bonuses when alignment is chosen
        //alignment has no relationship to skills, but is generally chosen after all skill dependent options are
        $form['field_fifth_alignment']['und']['#ajax'] = array(
            'callback' => 'character_attributes_alignment_ajax_callback',
            'wrapper' => 'alignment-check',
        );


        // print '<pre>';
        // print_r($form['field_fifth_lvl1_spells_prepared']);
        // print '</pre>';

        //logic for AJAX call
        if(!empty($form_state['values']['field_race'])) {
            //Dwarven logics
            if ($form_state['values']['field_race']['und'][0]['value'] == '1') {
                $con = $form_state['values']['field_fifth_constitution']['und'][0]['value'];
                unset($form_state['input']['field_fifth_constitution']['und'][0]['value']);
                $form['field_fifth_constitution']['und'][0]['value']['#default_value'] = 2 + $con;
                $conmod = $form_state['values']['field_fifth_constitution_modifie']['und'][0]['value'];
                unset($form_state['input']['field_fifth_constitution_modifie']['und'][0]['value']);
                $form['field_fifth_constitution_modifie']['und'][0]['value']['#default_value'] = $conmod + 1;
                unset($form_state['input']['field_fifth_speed']['und'][0]['value']);
                $form['field_fifth_speed']['und'][0]['value']['#default_value'] = 25;
                unset($form_state['input']['field_fifth_racial_features']['und'][0]['value']);
                $i = 0;
                while($i<count($dwarven_features)) {
                    unset($form_state['input']['field_fifth_racial_features']['und'][$i]['value']);
                    $form['field_fifth_racial_features']['und'][$i]['value']['#default_value'] = $dwarven_features[$i];
                    $i++;
                }
                unset($form_state['input']['field_fifth_weapon_proficiency']['und'][0]['value']);
                $form['field_fifth_weapon_proficiency']['und'][0]['value']['#default_value'] = 'All simple, Battleaxe, Warhammer';
                unset($form_state['input']['field_fifth_languages']['und'][0]['value']);
                $form['field_fifth_languages']['und'][0]['value']['#default_value'] = 'Common, Dwarven';
            } 
            //Elven logics
            if ($form_state['values']['field_race']['und'][0]['value'] == '2') {
                unset($form_state['input']['field_fifth_dexterity']['und'][0]['value']);
                $form['field_fifth_dexterity']['und'][0]['value']['#default_value'] = 2+$dex;
                unset($form_state['input']['field_fifth_dexterity_modifier']['und'][0]['value']);
                $form['field_fifth_dexterity_modifier']['und'][0]['value']['#default_value'] = $dexmod + 1;
                unset($form_state['input']['field_fifth_speed']['und'][0]['value']);
                $form['field_fifth_speed']['und'][0]['value']['#default_value'] = 30;
                unset($form_state['input']['field_fifth_racial_skill_prof']['und'][0]['value']);
                $form['field_fifth_racial_skill_prof']['und'][0]['value']['#default_value'] = "Perception";
                unset($form_state['input']['field_fifth_languages']['und'][0]['value']);
                $form['field_fifth_languages']['und'][0]['value']['#default_value'] = 'Common, Elven';
                $j = 0;
                while($j<count($elven_features)) {
                    unset($form_state['input']['field_fifth_racial_features']['und'][$j]['value']);
                    $form['field_fifth_racial_features']['und'][$j]['value']['#default_value'] = $elven_features[$j];
                    $j++;
                }
            }
        }
        //dwarf subrace logics
        if(!empty($form_state['values']['field_fifth_dwarven_sub_race'])) {
            //hill dwarf logics
            if ($form_state['values']['field_fifth_dwarven_sub_race']['und'][0]['value'] == '1') {
                $wis = $form_state['values']['field_fifth_wisdom']['und'][0]['value'] + 1;
                unset($form_state['input']['field_fifth_wisdom']['und'][0]['value']);
                $form['field_fifth_wisdom']['und'][0]['value']['#default_value'] = $wis;
                if ($wis % 2 == 0) {
                    $wismod = $form_state['values']['field_fifth_wisdom_modifier']['und'][0]['value'] + 1;
                    unset($form_state['input']['field_fifth_wisdom_modifier']['und'][0]['value']);
                    $form['field_fifth_wisdom_modifier']['und'][0]['value']['#default_value'] = $wismod;
                }
                unset($form_state['input']['field_fifth_subracial_features']['und'][0]['value']);
                $form['field_fifth_subracial_features']['und'][0]['value']['#default_value'] = "Dwarven Toughness. Your hit point maximum increases by 1, and it increases by 1 every time you gain a level.";
                $conmod = $form_state['values']['field_fifth_constitution_modifie']['und'][0]['value'];
                unset($form_state['input']['field_fifth_hit_points']['und'][0]['value']);
                $form['field_fifth_hit_points']['und'][0]['value']['#default_value'] = $conmod + 9;
            }
            //mountain dwarf logics
            if ($form_state['values']['field_fifth_dwarven_sub_race']['und'][0]['value'] == '2') {
                $str = $form_state['values']['field_fifth_strength']['und'][0]['value'] + 2;
                unset($form_state['input']['field_fifth_strength']['und'][0]['value']);
                $form['field_fifth_strength']['und'][0]['value']['#default_value'] = $str;
                $strmod = $form_state['values']['field_fifth_strength_modifier']['und'][0]['value'] + 1;
                unset($form_state['input']['field_fifth_strength_modifier']['und'][0]['value']);
                $form['field_fifth_strength_modifier']['und'][0]['value']['#default_value'] = $strmod;
            }
        }
        //elf subrace logics
        if(!empty($form_state['values']['field_fifth_elven_sub_race'])) {
            //high elf logics
            if ($form_state['values']['field_fifth_elven_sub_race']['und'][0]['value'] == '1') {
                $int = $form_state['values']['field_fifth_intelligence']['und'][0]['value'] + 1;
                unset($form_state['input']['field_fifth_intelligence']['und'][0]['value']);
                $form['field_fifth_intelligence']['und'][0]['value']['#default_value'] = $int;
                if ($int % 2 == 0) {
                    $intmod = $form_state['values']['field_fifth_intelligence_modifie']['und'][0]['value'] + 1;
                    unset($form_state['input']['field_fifth_intelligence_modifie']['und'][0]['value']);
                    $form['field_fifth_intelligence_modifie']['und'][0]['value']['#default_value'] = $intmod;
                }
                unset($form_state['input']['field_fifth_weapon_proficiency']['und'][0]['value']);
                $form['field_fifth_weapon_proficiency']['und'][0]['value']['#default_value'] = "All simple, Longsword, Shortsword, Longbow";
            }
            //wood elf logics
            if ($form_state['values']['field_fifth_elven_sub_race']['und'][0]['value'] == '2') {
                $wis = $form_state['values']['field_fifth_wisdom']['und'][0]['value'] + 1;
                unset($form_state['input']['field_fifth_wisdom']['und'][0]['value']);
                $form['field_fifth_wisdom']['und'][0]['value']['#default_value'] = $wis;
                if ($wis % 2 == 0) {
                    $wismod = $form_state['values']['field_fifth_wisdom_modifier']['und'][0]['value'] + 1;
                    unset($form_state['input']['field_fifth_wisdom_modifier']['und'][0]['value']);
                    $form['field_fifth_wisdom_modifier']['und'][0]['value']['#default_value'] = $wismod;
                }
                unset($form_state['input']['field_fifth_weapon_proficiency']['und'][0]['value']);
                $form['field_fifth_weapon_proficiency']['und'][0]['value']['#default_value'] = "All simple, Longsword, Shortsword, Longbow";
                unset($form_state['input']['field_fifth_speed']['und'][0]['value']);
                $form['field_fifth_speed']['und'][0]['value']['#default_value'] = "35";
                unset($form_state['input']['field_fifth_subracial_features']['und'][0]['value']);
                $form['field_fifth_subracial_features']['und'][0]['value']['#default_value'] = "Mask of the Wild. 
You can attempt to hide even when you are only lightly obscured by foliage, heavy rain, falling snow, mist, and other natural phenomena.";
            }
            //drow logics
            if ($form_state['values']['field_fifth_elven_sub_race']['und'][0]['value'] == '3') {
                $cha = $form_state['values']['field_fifth_charisma']['und'][0]['value'] + 1;
                unset($form_state['input']['field_fifth_charisma']['und'][0]['value']);
                $form['field_fifth_charisma']['und'][0]['value']['#default_value'] = $cha;
                if ($cha % 2 == 0) {
                    $chamod = $form_state['values']['field_fifth_charisma_modifier']['und'][0]['value'] + 1;
                    unset($form_state['input']['field_fifth_charisma_modifier']['und'][0]['value']);
                    $form['field_fifth_charisma_modifier']['und'][0]['value']['#default_value'] = $chamod;
                }
                unset($form_state['input']['field_fifth_weapon_proficiency']['und'][0]['value']);
                $form['field_fifth_weapon_proficiency']['und'][0]['value']['#default_value'] = "All simple, Rapier, Shortsword, Hand crossbow";
                $j = 0;
                while($j<count($drow_features)) {
                    unset($form_state['input']['field_fifth_subracial_features']['und'][$j]['value']);
                    $form['field_fifth_subracial_features']['und'][$j]['value']['#default_value'] = $drow_features[$j];
                    $j++;
                }
                $form['field_fifth_racial_spell']['und']['#description'] = 'Dancing Lights';
            }
        }
        //domain logics
        if(!empty($form_state['values']['field_fifth_cleric_domain'])) {
            //knowledge domain
            if ($form_state['values']['field_fifth_cleric_domain']['und'][0]['value'] == 'Knowledge') {
                $i = 0;
                while($i<count($knowledge_features)) {
                    unset($form_state['input']['field_fifth_domain_features']['und'][$i]['value']);
                    $form['field_fifth_domain_features']['und'][$i]['value']['#default_value'] = $knowledge_features[$i];
                    $i++;
                }
                $form['field_fifth_domain_spells']['und']['#description'] = 'Command, Identify';
                //at level 2
                if ($form_state['values']['field_fifth_cleric_level']['und'][0]['value'] >= '2') {
                    unset($form_state['input']['field_fifth_domain_features']['und'][2]['value']);
                    $form['field_fifth_domain_features']['und'][2]['value']['#default_value'] = "Channel Divinity: Knowledge of the Ages.
Starting at 2nd level, you can use your Channel Divinity to tap into a divine well of knowledge. As an action, you choose one skill or tool. For 10 minutes, you have proficiency with the chosen skill or tool.";
                }
            }
            //life domain
            if ($form_state['values']['field_fifth_cleric_domain']['und'][0]['value'] == 'Life') {
                $i = 0;
                while($i<count($life_features)) {
                    unset($form_state['input']['field_fifth_domain_features']['und'][$i]['value']);
                    $form['field_fifth_domain_features']['und'][$i]['value']['#default_value'] = $life_features[$i];
                    $i++;
                }
                unset($form_state['input']['field_fifth_armor_proficiency']['und'][0]['value']);
                $form['field_fifth_armor_proficiency']['und'][0]['value']['#default_value'] = 'Light, Medium, Heavy, Shields';
                $form['field_fifth_domain_spells']['und']['#description'] = 'Bless, Cure Wounds';
                //at level 2
                if ($form_state['values']['field_fifth_cleric_level']['und'][0]['value'] >= '2') {
                    unset($form_state['input']['field_fifth_domain_features']['und'][1]['value']);
                    $form['field_fifth_domain_features']['und'][1]['value']['#default_value'] = "Channel Divinity: Preserve Life.
Starting at 2nd level, you can use your Channel Divinity to heal the badly injured.
As an action, you present your holy symbol and evoke healing energy that can restore a number of hit points equal to five times your cleric level. Choose any creatures within 30 feet of you, and divide those hit points among them. This feature can restore a creature to no more than half of its hit point maximum. You can’t use this feature on an undead or a construct.";
                }
            }
            //level logic
            if ($form_state['values']['field_fifth_cleric_level']['und'][0]['value'] >= '2') {
                unset($form_state['input']['field_fifth_class_features']['und'][8]['value']);
                $form['field_fifth_class_features']['und'][8]['value']['#default_value'] = "Channel Divinity.
At 2nd level, you gain the ability to channel divine energy directly from your deity, using that energy to fuel magical effects. You start with two such effects: Turn Undead and an effect determined by your domain. Some domains grant you additional effects as you advance in levels, as noted in the domain description.
When you use your Channel Divinity, you choose which effect to create. You must then finish a short or long rest to use your Channel Divinity again.
Some Channel Divinity effects require saving throws. When you use such an effect from this class, the DC equals your cleric spell save DC.
Beginning at 6th level, you can use your Channel Divinity twice between rests, and beginning at 18th level. you can use it three times between rests. When you finish a short or long rest, you regain your expended uses.";
                unset($form_state['input']['field_fifth_class_features']['und'][9]['value']);
                $form['field_fifth_class_features']['und'][9]['value']['#default_value'] = "Channel Divinity: Turn Undead.
As an action, you present your holy symbol and speak a prayer censuring the undead. Each undead that can see or hear you within 30 feet of you must make a Wisdom saving throw. If the creature fails its saving throw, it is turned for 1 minute or until it takes any damage.
A turned creature must spend its turns trying to move as far away from you as it can, and it can’t willingly move to a space within 30 feet of you. It also can’t take reactions. For its action, it can use only the Dash action or try to escape from an effect that prevents it from moving. If there’s nowhere to move, the creature can use the Dodge action.";
                $form['field_fifth_lvl1_spells_prepared']['und']['#description'] = "<p>Choose 3</p>
<p>Choose from: Bane, Bless, Command, Create or Destroy Water, Cure Wounds, Detect Evil and Good, Detect Magic, Detect Poison and Disease, Guiding Bolt, Healing Word, Inflict Wounds, Protection from Evil and Good, Purify Food and Drink, Sanctuary, Shield of Faith</p>";
            }
        }

        //background logics
        if(!empty($form_state['values']['field_fifth_backgrounds'])) {
            unset($form_state['input']['field_fifth_starting_money']['und'][0]['value']);
            $form['field_fifth_starting_money']['und'][0]['value']['#default_value'] = '15 GP';
            //acolyte background logics
            if ($form_state['values']['field_fifth_backgrounds']['und'][0]['value'] == '1') {
                $i = 0;
                while($i<count($acolyte_features)) {
                    unset($form_state['input']['field_fifth_background_feature']['und'][$i]['value']);
                    $form['field_fifth_background_feature']['und'][$i]['value']['#default_value'] = $acolyte_features[$i];
                    $i++;
                }
                unset($form_state['input']['field_fifth_background_skills']['und'][0]['value']);
                $form['field_fifth_background_skills']['und'][0]['value']['#default_value'] = 'Insight, Religion';
                $form['field_fifth_background_bundle']['und']['#description'] = 'Choose Acolyte';
            }
            //charlatan background logics
            if ($form_state['values']['field_fifth_backgrounds']['und'][0]['value'] == '2') {
                $i = 0;
                while($i<count($charlatan_features)) {
                    unset($form_state['input']['field_fifth_background_feature']['und'][$i]['value']);
                    $form['field_fifth_background_feature']['und'][$i]['value']['#default_value'] = $charlatan_features[$i];
                    $i++;
                }
                unset($form_state['input']['field_fifth_background_skills']['und'][0]['value']);
                $form['field_fifth_background_skills']['und'][0]['value']['#default_value'] = 'Deception, Sleight of Hand';
                unset($form_state['input']['field_fifth_background_tool_prof']['und'][0]['value']);
                $form['field_fifth_background_tool_prof']['und'][0]['value']['#default_value'] = 'Disguise kit, Forgery kit';
                $form['field_fifth_background_bundle']['und']['#description'] = 'Choose Charlatan';
            }
        }
        if(!empty($form_state['values']['field_fifth_alignment'])) {
            //rewrite skill values
            //str
            $strmod = $form_state['values']['field_fifth_strength_modifier']['und'][0]['value'];
            unset($form_state['input']['field_fifth_athletics']['und'][0]['value']);
            $form['field_fifth_athletics']['und'][0]['value']['#default_value'] = $strmod;
            //dex
            $dexmod = $form_state['values']['field_fifth_dexterity_modifier']['und'][0]['value'];
            unset($form_state['input']['field_fifth_initiative']['und'][0]['value']);
            unset($form_state['input']['field_fifth_acrobatics']['und'][0]['value']);
            unset($form_state['input']['field_fifth_sleight_of_hand']['und'][0]['value']);
            unset($form_state['input']['field_fifth_stealth']['und'][0]['value']);
            unset($form_state['input']['field_fifth_armor_class']['und'][0]['value']);
            if ($form_state['values']['field_fifth_backgrounds']['und'][0]['value'] == '2') {
                $form['field_fifth_sleight_of_hand']['und'][0]['value']['#default_value'] = $dexmod + 2;
                $form['field_fifth_sleight_of_hand_prof']['und']['#attributes'] = array('checked' => 'checked');
            } else {
                $form['field_fifth_sleight_of_hand']['und'][0]['value']['#default_value'] = $dexmod;
            }
            $form['field_fifth_initiative']['und'][0]['value']['#default_value'] = 
            $form['field_fifth_acrobatics']['und'][0]['value']['#default_value'] = 
            $form['field_fifth_stealth']['und'][0]['value']['#default_value'] = 
            $dexmod;
            //TODO:fix if statement to correctly check entity field
            // if ($form_state['values']['field_fifth_cleric_armor_choice']['und'][0]['value'] == 'Scale mail (47)') {
            //     $form['field_fifth_armor_class']['und'][0]['value']['#default_value'] = 14 + $dexmod;
            // }
            //int
            $intmod = $form_state['values']['field_fifth_intelligence_modifie']['und'][0]['value'];
            unset($form_state['input']['field_fifth_arcana']['und'][0]['value']);
            unset($form_state['input']['field_fifth_history']['und'][0]['value']);
            unset($form_state['input']['field_fifth_investigation']['und'][0]['value']);
            unset($form_state['input']['field_fifth_nature']['und'][0]['value']);
            unset($form_state['input']['field_fifth_religion']['und'][0]['value']);
            if (($form_state['values']['field_fifth_backgrounds']['und'][0]['value'] == '1') || 
            ($form_state['values']['field_fifth_knwldge_domainskills']['und'][0]['value'] == 'Religion') ||
            ($form_state['values']['field_fifth_knwldge_domainskills']['und'][1]['value'] == 'Religion') ||
            ($form_state['values']['field_fifth_cleric_skills']['und'][0]['value'] == 'Religion') ||
            ($form_state['values']['field_fifth_cleric_skills']['und'][1]['value'] == 'Religion')) {
                $form['field_fifth_religion']['und'][0]['value']['#default_value'] = $intmod + 2;
                $form['field_fifth_religion_proficiency']['und']['#attributes'] = array('checked' => 'checked');
            } else {
                $form['field_fifth_religion']['und'][0]['value']['#default_value'] = $intmod;
            }
            if (($form_state['values']['field_fifth_knwldge_domainskills']['und'][0]['value'] == 'Nature') || 
            ($form_state['values']['field_fifth_knwldge_domainskills']['und'][1]['value'] == 'Nature')) {
                $form['field_fifth_nature']['und'][0]['value']['#default_value'] = $intmod + 2;
                $form['field_fifth_nature_proficiency']['und']['#attributes'] = array('checked' => 'checked');
            } else {
                $form['field_fifth_nature']['und'][0]['value']['#default_value'] = $intmod;
            }
            if (($form_state['values']['field_fifth_knwldge_domainskills']['und'][0]['value'] == 'History') || 
            ($form_state['values']['field_fifth_knwldge_domainskills']['und'][1]['value'] == 'History') || 
            ($form_state['values']['field_fifth_cleric_skills']['und'][0]['value'] == 'History') || 
            ($form_state['values']['field_fifth_cleric_skills']['und'][1]['value'] == 'History')) {
                $form['field_fifth_history']['und'][0]['value']['#default_value'] = $intmod + 2;
                $form['field_fifth_history_proficiency']['und']['#attributes'] = array('checked' => 'checked');
            } else {
                $form['field_fifth_history']['und'][0]['value']['#default_value'] = $intmod;
            }
            if (($form_state['values']['field_fifth_knwldge_domainskills']['und'][0]['value'] == 'Arcana') || 
            ($form_state['values']['field_fifth_knwldge_domainskills']['und'][1]['value'] == 'Arcana')) {
                $form['field_fifth_arcana']['und'][0]['value']['#default_value'] = $intmod + 2;
                $form['field_fifth_arcana_proficiency']['und']['#attributes'] = array('checked' => 'checked');
            } else {
                $form['field_fifth_arcana']['und'][0]['value']['#default_value'] = $intmod;
            }
            $form['field_fifth_investigation']['und'][0]['value']['#default_value'] = $intmod;
            //wis
            $wismod = $form_state['values']['field_fifth_wisdom_modifier']['und'][0]['value'];
            unset($form_state['input']['field_fifth_animal_handling']['und'][0]['value']);
            unset($form_state['input']['field_fifth_insight']['und'][0]['value']);
            unset($form_state['input']['field_fifth_medicine']['und'][0]['value']);
            unset($form_state['input']['field_fifth_perception']['und'][0]['value']);
            unset($form_state['input']['field_fifth_survival']['und'][0]['value']);
            if (($form_state['values']['field_fifth_cleric_skills']['und'][0]['value'] == 'Insight') || 
            ($form_state['values']['field_fifth_cleric_skills']['und'][1]['value'] == 'Insight') || 
            ($form_state['values']['field_fifth_backgrounds']['und'][0]['value'] == '1')) {
                $form['field_fifth_insight']['und'][0]['value']['#default_value'] = $wismod + 2;
                $form['field_fifth_insight_proficiency']['und']['#attributes'] = array('checked' => 'checked');
            } else {
                $form['field_fifth_insight']['und'][0]['value']['#default_value'] = $wismod;
            }
            if (($form_state['values']['field_fifth_cleric_skills']['und'][0]['value'] == 'Medicine') || 
            ($form_state['values']['field_fifth_cleric_skills']['und'][1]['value'] == 'Medicine')) {
                $form['field_fifth_medicine']['und'][0]['value']['#default_value'] = $wismod + 2;
                $form['field_fifth_medicine_proficiency']['und']['#attributes'] = array('checked' => 'checked');
            } else {
                $form['field_fifth_medicine']['und'][0]['value']['#default_value'] = $wismod;
            }
            if ($form_state['values']['field_race']['und'][0]['value'] == '2') {
                $form['field_fifth_perception']['und'][0]['value']['#default_value'] = $wismod + 2;
                $form['field_fifth_perception_prof']['und']['#attributes'] = array('checked' => 'checked');
            } else {
                $form['field_fifth_perception']['und'][0]['value']['#default_value'] = $wismod;
            }
            $form['field_fifth_animal_handling']['und'][0]['value']['#default_value'] = $wismod;
            $form['field_fifth_survival']['und'][0]['value']['#default_value'] = $wismod;
            //cha
            $chamod = $form_state['values']['field_fifth_charisma_modifier']['und'][0]['value'];
            unset($form_state['input']['field_fifth_deception']['und'][0]['value']);
            unset($form_state['input']['field_fifth_intimidation']['und'][0]['value']);
            unset($form_state['input']['field_fifth_performance']['und'][0]['value']);
            unset($form_state['input']['field_fifth_persuasion']['und'][0]['value']);
            if (($form_state['values']['field_fifth_cleric_skills']['und'][0]['value'] == 'Persuasion') || 
            ($form_state['values']['field_fifth_cleric_skills']['und'][1]['value'] == 'Persuasion')) {
                $form['field_fifth_persuasion']['und'][0]['value']['#default_value'] = $chamod + 2;
                $form['field_fifth_persuasion_prof']['und']['#attributes'] = array('checked' => 'checked');
            } else {
                $form['field_fifth_persuasion']['und'][0]['value']['#default_value'] = $chamod;
            }
            if ($form_state['values']['field_fifth_backgrounds']['und'][0]['value'] == '2') {
                $form['field_fifth_deception']['und'][0]['value']['#default_value'] = $chamod + 2;
                $form['field_fifth_deception_prof']['und']['#attributes'] = array('checked' => 'checked');
            } else {
                $form['field_fifth_deception']['und'][0]['value']['#default_value'] = $chamod;
            }
            $form['field_fifth_intimidation']['und'][0]['value']['#default_value'] = $chamod;
            $form['field_fifth_performance']['und'][0]['value']['#default_value'] = $chamod;
            //con
            $conmod = $form_state['values']['field_fifth_constitution_modifie']['und'][0]['value'];
            unset($form_state['input']['field_fifth_hit_points']['und'][0]['value']);
            if ($form_state['values']['field_fifth_cleric_level']['und'][0]['value'] >= '2') {
                if ($form_state['values']['field_fifth_dwarven_sub_race']['und'][0]['value'] == '1') {
                    $form['field_fifth_hit_points']['und'][0]['value']['#default_value'] = rand(1, 8) + (2 * $conmod) + 10;
                } else {
                    $form['field_fifth_hit_points']['und'][0]['value']['#default_value'] = rand(1, 8) + (2 * $conmod) + 8;
                }
            } else {
                if ($form_state['values']['field_fifth_dwarven_sub_race']['und'][0]['value'] == '1') {
                    $form['field_fifth_hit_points']['und'][0]['value']['#default_value'] = $conmod + 9;
                } else {
                    $form['field_fifth_hit_points']['und'][0]['value']['#default_value'] = $conmod + 8;
                }
            }
        }
    }   
}

// AJAX callback function
function character_attributes_race_ajax_callback($form, $form_state) {
    $commands = array();
    $commands[] = ajax_command_replace('#race-check-con', drupal_render($form['field_fifth_constitution']));
    $commands[] = ajax_command_replace('#race-check-speed', drupal_render($form['field_fifth_speed']));
    $commands[] = ajax_command_replace('#race-check-features', drupal_render($form['field_fifth_racial_features']));
    $commands[] = ajax_command_replace('#race-check-conmod', drupal_render($form['field_fifth_constitution_modifie']));
    $commands[] = ajax_command_replace('#race-check-hit-dice', drupal_render($form['field_fifth_hit_dice']));
    $commands[] = ajax_command_replace('#race-check-weapon-proficiency', drupal_render($form['field_fifth_weapon_proficiency']));
    $commands[] = ajax_command_replace('#race-check-language', drupal_render($form['field_fifth_languages']));
    $commands[] = ajax_command_replace('#race-check-dexterity', drupal_render($form['field_fifth_dexterity']));
    $commands[] = ajax_command_replace('#race-check-dexmod', drupal_render($form['field_fifth_dexterity_modifier']));
    $commands[] = ajax_command_replace('#race-check-skill-prof', drupal_render($form['field_fifth_racial_skill_prof']));
    return array('#type' => 'ajax', '#commands' => $commands);
}

function character_attributes_dwarven_subrace_ajax_callback($form, $form_state) {
    $commands = array();
    $commands[] = ajax_command_replace('#subrace-check-wis', drupal_render($form['field_fifth_wisdom']));
    $commands[] = ajax_command_replace('#subrace-check-features', drupal_render($form['field_fifth_subracial_features']));
    $commands[] = ajax_command_replace('#subrace-check-hp', drupal_render($form['field_fifth_hit_points']));
    $commands[] = ajax_command_replace('#subrace-check-strength', drupal_render($form['field_fifth_strength']));
    $commands[] = ajax_command_replace('#subrace-check-wismod', drupal_render($form['field_fifth_wisdom_modifier']));
    $commands[] = ajax_command_replace('#subrace-check-strmod', drupal_render($form['field_fifth_strength_modifier']));
    return array('#type' => 'ajax', '#commands' => $commands);
}

function character_attributes_elven_subrace_ajax_callback($form, $form_state) {
    $commands = array();
    $commands[] = ajax_command_replace('#subrace-elven-check-int', drupal_render($form['field_fifth_intelligence']));
    $commands[] = ajax_command_replace('#subrace-elven-check-intmod', drupal_render($form['field_fifth_intelligence_modifie']));
    $commands[] = ajax_command_replace('#subrace-check-wis', drupal_render($form['field_fifth_wisdom']));
    $commands[] = ajax_command_replace('#subrace-check-wismod', drupal_render($form['field_fifth_wisdom_modifier']));
    $commands[] = ajax_command_replace('#subrace-elven-check-cha', drupal_render($form['field_fifth_charisma']));
    $commands[] = ajax_command_replace('#subrace-elven-check-chamod', drupal_render($form['field_fifth_charisma_modifier']));
    $commands[] = ajax_command_replace('#race-check-weapon-proficiency', drupal_render($form['field_fifth_weapon_proficiency']));
    $commands[] = ajax_command_replace('#race-check-speed', drupal_render($form['field_fifth_speed']));
    $commands[] = ajax_command_replace('#subrace-check-features', drupal_render($form['field_fifth_subracial_features']));
    $commands[] = ajax_command_replace('#subrace-elven-check-spell', drupal_render($form['field_fifth_racial_spell']));
    return array('#type' => 'ajax', '#commands' => $commands);
}

function character_attributes_domain_ajax_callback($form, $form_state) {
    $commands = array();
    $commands[] = ajax_command_replace('#domain-check-features', drupal_render($form['field_fifth_domain_features']));
    $commands[] = ajax_command_replace('#domain-check-armor', drupal_render($form['field_fifth_armor_proficiency']));
    $commands[] = ajax_command_replace('#domain-check-spells', drupal_render($form['field_fifth_domain_spells']));
    $commands[] = ajax_command_replace('#domain-check-class-features', drupal_render($form['field_fifth_class_features']));
    $commands[] = ajax_command_replace('#domain-check-class-spells-level-2', drupal_render($form['field_fifth_lvl1_spells_prepared']));
    return array('#type' => 'ajax', '#commands' => $commands);
}

function character_attributes_background_ajax_callback($form, $form_state) {
    $commands = array();
    $commands[] = ajax_command_replace('#background-check-feature', drupal_render($form['field_fifth_background_feature']));
    $commands[] = ajax_command_replace('#background-check-skills', drupal_render($form['field_fifth_background_skills']));
    $commands[] = ajax_command_replace('#background-check-tool-proficiency', drupal_render($form['field_fifth_background_tool_prof']));
    $commands[] = ajax_command_replace('#background-check-money', drupal_render($form['field_fifth_starting_money']));
    $commands[] = ajax_command_replace('#background-check-bundle', drupal_render($form['field_fifth_background_bundle']));
    return array('#type' => 'ajax', '#commands' => $commands);
}

function character_attributes_alignment_ajax_callback($form, $form_state) {
    $commands = array();
    $commands[] = ajax_command_replace('#skill-check-rewrite-athletics', drupal_render($form['field_fifth_athletics']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-initiative', drupal_render($form['field_fifth_initiative']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-acrobatics', drupal_render($form['field_fifth_acrobatics']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-sleight-of-hand', drupal_render($form['field_fifth_sleight_of_hand']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-stealth', drupal_render($form['field_fifth_stealth']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-arcana', drupal_render($form['field_fifth_arcana']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-history', drupal_render($form['field_fifth_history']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-investigation', drupal_render($form['field_fifth_investigation']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-nature', drupal_render($form['field_fifth_nature']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-religion', drupal_render($form['field_fifth_religion']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-animal-handling', drupal_render($form['field_fifth_animal_handling']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-insight', drupal_render($form['field_fifth_insight']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-medicine', drupal_render($form['field_fifth_medicine']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-perception', drupal_render($form['field_fifth_perception']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-survival', drupal_render($form['field_fifth_survival']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-deception', drupal_render($form['field_fifth_deception']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-intimidation', drupal_render($form['field_fifth_intimidation']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-performance', drupal_render($form['field_fifth_performance']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-persuasion', drupal_render($form['field_fifth_persuasion']));
    $commands[] = ajax_command_replace('#prof-check-arcana', drupal_render($form['field_fifth_arcana_proficiency']));
    $commands[] = ajax_command_replace('#prof-check-deception', drupal_render($form['field_fifth_deception_prof']));
    $commands[] = ajax_command_replace('#prof-check-history', drupal_render($form['field_fifth_history_proficiency']));
    $commands[] = ajax_command_replace('#prof-check-insight', drupal_render($form['field_fifth_insight_proficiency']));
    $commands[] = ajax_command_replace('#prof-check-medicine', drupal_render($form['field_fifth_medicine_proficiency']));
    $commands[] = ajax_command_replace('#prof-check-nature', drupal_render($form['field_fifth_nature_proficiency']));
    $commands[] = ajax_command_replace('#prof-check-perception', drupal_render($form['field_fifth_perception_prof']));
    $commands[] = ajax_command_replace('#prof-check-persuasion', drupal_render($form['field_fifth_persuasion_prof']));
    $commands[] = ajax_command_replace('#prof-check-religion', drupal_render($form['field_fifth_religion_proficiency']));
    $commands[] = ajax_command_replace('#prof-check-sleight-of-hand', drupal_render($form['field_fifth_sleight_of_hand_prof']));
    $commands[] = ajax_command_replace('#subrace-check-hp', drupal_render($form['field_fifth_hit_points']));
    $commands[] = ajax_command_replace('#skill-check-rewrite-ac', drupal_render($form['field_fifth_armor_class']));
    return array('#type' => 'ajax', '#commands' => $commands);
}

function character_attributes_form_field_ui_field_edit_form_alter(&$form, &$form_state, $form_id) {
  // Increase the max cardinality to 20
  $range = drupal_map_assoc(range(1, 20));
  $new_options =  array(FIELD_CARDINALITY_UNLIMITED => t('Unlimited')) + $range;

  // Change the options
  $form['field']['cardinality']['#options'] = $new_options;
}