<?php

function character_attributes_form_alter(&$form, &$form_state, $form_id, $node) {
    // find form id on target page
    // print_r($form_id);
    if ($form_id == 'fifth_cleric_character_node_form') {
        // print entire form so that you can find a specific value
        // print '<pre>';
        // print_r($form);
        // print '</pre>';
        
        $number_of_attributes = 6;
        $attribute = array();
        $modifiers = array();

        while ($number_of_attributes > 0) {
            $number_of_attributes--;
        
            $dice_array = array();
            $number_of_dice = 4;
            $dice_min = 1;
            $dice_max = 6;
            
            while ($number_of_dice > 0) {
                $number_of_dice--;
                array_push($dice_array, (rand($dice_min, $dice_max)));
            }
            
            sort ($dice_array, SORT_NUMERIC);
            array_shift($dice_array);
            $dice_roll_total = array_sum($dice_array);
            array_push($attribute, $dice_roll_total);
        }   
        
        sort ($attribute, SORT_NUMERIC);
            
        //for clerics only
        $wis = $attribute[5];
        $dex = $attribute[4];
        $con = $attribute[3];
        $str = $attribute[2];
        $cha = $attribute[1];
        $int = $attribute[0];
        
        // $items = field_get_items('node', $node, 'field_race');
        // $item = array_shift($items);
        // $race = $item[0]['value'];
        
        // $race = $form['field_fifth_constitution']['und'];
        // print '<pre>';
        // print_r($race);
        // print '</pre>';

        
        //translates attributes to modifiers
        foreach ($attribute as $stat) {
            if ($stat == 3) {
                array_push($modifiers, -4);
            } elseif ($stat == 4 || $stat == 5) {
                array_push($modifiers, -3);
            } elseif ($stat == 6 || $stat == 7) {
                array_push($modifiers, -2);
            } elseif ($stat == 8 || $stat == 9) {
                array_push($modifiers, -1);
            } elseif ($stat == 10 || $stat == 11) {
                array_push($modifiers, 0);
            } elseif ($stat == 12 || $stat == 13) {
                array_push($modifiers, 1);
            } elseif ($stat == 14 || $stat == 15) {
                array_push($modifiers, 2);
            } elseif ($stat == 16 || $stat == 17) {
                array_push($modifiers, 3);
            } else {
                array_push($modifiers, 4);
            }
        }
        
        sort ($modifiers, SORT_NUMERIC);

        $wismod = $modifiers[5];
        $dexmod = $modifiers[4];
        $conmod = $modifiers[3];
        $strmod = $modifiers[2];
        $chamod = $modifiers[1];
        $intmod = $modifiers[0];
        

        //hiding class field because it is needed for conditional field logic, but not needed for interface
        $form['field_fifth_class']['und']['#prefix'] = "<div style='display: none'>";
        $form['field_fifth_class']['und']['#suffix'] = "</div>";
        
        //setting default attribute values
        $form['field_fifth_strength']['und']['0']['value']['#default_value'] = $str;
        $form['field_fifth_dexterity']['und']['0']['value']['#default_value'] = $dex;
        $form['field_fifth_constitution']['und']['0']['value']['#default_value'] = $con;
        $form['field_fifth_intelligence']['und']['0']['value']['#default_value'] = $int;
        $form['field_fifth_wisdom']['und']['0']['value']['#default_value'] = $wis;
        $form['field_fifth_charisma']['und']['0']['value']['#default_value'] = $cha;
        
        $form['field_fifth_strength_modifier']['und']['0']['value']['#default_value'] = $strmod;
        $form['field_fifth_dexterity_modifier']['und']['0']['value']['#default_value'] = $dexmod;
        $form['field_fifth_constitution_modifie']['und']['0']['value']['#default_value'] = $conmod;
        $form['field_fifth_intelligence_modifie']['und']['0']['value']['#default_value'] = $intmod;
        $form['field_fifth_wisdom_modifier']['und']['0']['value']['#default_value'] = $wismod;
        $form['field_fifth_charisma_modifier']['und']['0']['value']['#default_value'] = $chamod;
        
        //setting default skill/initiative values
        $form['field_fifth_athletics']['und']['0']['value']['#default_value'] = $strmod;
        $form['field_fifth_initiative']['und']['0']['value']['#default_value'] =
        $form['field_fifth_acrobatics']['und']['0']['value']['#default_value'] =
        $form['field_fifth_sleight_of_hand']['und']['0']['value']['#default_value'] =
        $form['field_fifth_stealth']['und']['0']['value']['#default_value'] = $dexmod;
        $form['field_fifth_arcana']['und']['0']['value']['#default_value'] =
        $form['field_fifth_history']['und']['0']['value']['#default_value'] =
        $form['field_fifth_investigation']['und']['0']['value']['#default_value'] =
        $form['field_fifth_nature']['und']['0']['value']['#default_value'] =
        $form['field_fifth_religion']['und']['0']['value']['#default_value'] = $intmod;
        $form['field_fifth_animal_handling']['und']['0']['value']['#default_value'] =
        $form['field_fifth_insight']['und']['0']['value']['#default_value'] =
        $form['field_fifth_medicine']['und']['0']['value']['#default_value'] =
        $form['field_fifth_perception']['und']['0']['value']['#default_value'] =
        $form['field_fifth_survival']['und']['0']['value']['#default_value'] = $wismod;
        $form['field_fifth_deception']['und']['0']['value']['#default_value'] =
        $form['field_fifth_intimidation']['und']['0']['value']['#default_value'] =
        $form['field_fifth_performance']['und']['0']['value']['#default_value'] =
        $form['field_fifth_persuasion']['und']['0']['value']['#default_value'] = $chamod;
        
        //adding AJAX to check race and add bonuses accordingly
        //this is the part being refreshed
        $form['field_fifth_constitution']['und']['#prefix'] = '<div id="race-check-con">';
        $form['field_fifth_speed']['und']['#prefix'] = '<div id="race-check-speed">';
        $form['field_fifth_racial_features']['und']['#prefix'] = '<div id="race-check-features">';
        $form['field_fifth_constitution_modifie']['und']['#prefix'] = '<div id="race-check-conmod">';
        $form['field_fifth_hit_dice']['und']['#prefix'] = '<div id="race-check-hit-dice">';

        $form['field_fifth_constitution']['und']['#suffix'] = 
        $form['field_fifth_speed']['und']['#suffix'] = 
        $form['field_fifth_racial_features']['und']['#suffix'] = 
        $form['field_fifth_constitution_modifie']['und']['#suffix'] = 
        $form['field_fifth_hit_dice']['und']['#suffix'] = 
            '</div>';

        $form['field_fifth_wisdom']['und']['#prefix'] = '<div id="subrace-check-wis">';
        $form['field_fifth_subracial_features']['und']['#prefix'] = '<div id="subrace-check-features">';
        $form['field_fifth_hit_points']['und']['#prefix'] = '<div id="subrace-check-hp">';
        
        $form['field_fifth_wisdom']['und']['#suffix'] = 
        $form['field_fifth_hit_points']['und']['#suffix'] = 
        $form['field_fifth_subracial_features']['und']['#suffix'] = '</div>';

        $dwarven_features = array();
        $dwarven_features[] = "Age. Dwarves mature at the same rate as humans, but they’re considered young until they reach the age of 50. On average, they live about 350 years.";
        $dwarven_features[] = "Alignment. Most dwarves are lawful, believing firmly in the benefits of a well-ordered society. They tend toward good as well, with a strong sense of fair play and a belief that everyone deserves to share in the benefits of a just order.";
        $dwarven_features[] = "Size. Dwarves stand between 4 and 5 feet tall and average about 150 pounds. Your size is Medium.";
        $dwarven_features[] = "Darkvision. Accustomed to life underground, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.";
        $dwarven_features[] = "Dwarven Resilience. You have advantage on saving throws against poison, and you have resistance against poison damage.";
        $dwarven_features[] = "Dwarven Combat Training. You have proficiency with the battleaxe, handaxe, throwing hammer, and warhammer.";
        $dwarven_features[] = "Tool Proficiency. You gain proficiency with the artisan’s tools of your choice: smith’s tools, brewer’s supplies, or mason’s tools.";
        $dwarven_features[] = "Stonecunning. Whenever you make an Intelligence (History) check related to the origin of stonework, you are considered proficient in the History skill and add double your proficiency bonus to the check, instead of your normal proficiency bonus.";
        $dwarven_features[] = "Languages. You can speak, read, and write Common and Dwarvish. Dwarvish is full of hard consonants and guttural sounds, and those characteristics spill over into whatever other language a dwarf might speak.";
        
        //triggers the replacement
        $form['field_race']['und']['#ajax'] = array(
            'callback' => 'character_attributes_dwarven_ajax_callback',
            'wrapper' => 'race-check',
        );
        
        $form['field_fifth_dwarven_sub_race']['und']['#ajax'] = array(
            'callback' => 'character_attributes_custom_ajax_callback2',
            'wrapper' => 'subrace-check',
        );

        
        // print '<pre>';
        // print_r($form['field_fifth_racial_features']);
        // print '</pre>';
        
                    
        //logic for AJAX call
        //Dwarven logics
        if(!empty($form_state['values']['field_race'])) {
            if ($form_state['values']['field_race']['und'][0]['value']='Dwarf') {
                $current_con = $form_state['input']['field_fifth_constitution']['und'][0]['value'];
                unset($form_state['input']['field_fifth_constitution']['und'][0]['value']);
                $form['field_fifth_constitution']['und'][0]['value']['#default_value'] = 2+$current_con;
                $current_conmod = $form_state['input']['field_fifth_constitution_modifie']['und'][0]['value'];
                unset($form_state['input']['field_fifth_constitution_modifie']['und'][0]['value']);
                $form['field_fifth_constitution_modifie']['und'][0]['value']['#default_value'] = $current_conmod + 1;
                unset($form_state['input']['field_fifth_speed']['und'][0]['value']);
                $form['field_fifth_speed']['und'][0]['value']['#default_value'] = 25;
                unset($form_state['input']['field_fifth_racial_features']['und'][0]['value']);
                $i = 0;
                while($i<count($dwarven_features)) {
                    unset($form_state['input']['field_fifth_racial_features']['und'][$i]['value']);
                    $form['field_fifth_racial_features']['und'][$i]['value']['#default_value'] = $dwarven_features[$i];
                    $i++;
                }
                unset($form_state['input']['field_fifth_hit_dice']['und'][0]['value']);
                $form['field_fifth_hit_dice']['und'][0]['value']['#default_value'] = '1d8';
            } 
        }
        if(!empty($form_state['values']['field_fifth_dwarven_sub_race'])) {
            if ($form_state['values']['field_fifth_dwarven_sub_race']['und'][0]['value'] = 'Hill') {
                $current_wis = $form_state['input']['field_fifth_wisdom']['und'][0]['value'];
                unset($form_state['input']['field_fifth_wisdom']['und'][0]['value']);
                $form['field_fifth_wisdom']['und'][0]['value']['#default_value'] = 1 + $current_wis;
                unset($form_state['input']['field_fifth_subracial_features']['und'][0]['value']);
                $form['field_fifth_subracial_features']['und'][0]['value']['#default_value'] = "Dwarven Toughness. Your hit point maximum increases by 1, and it increases by 1 every time you gain a level.";
                unset($form_state['input']['field_fifth_hit_points']['und'][0]['value']);
                $form['field_fifth_hit_points']['und'][0]['value']['#default_value'] = $current_conmod + 9;
            }
        }
    }   
}

// AJAX callback function
function character_attributes_dwarven_ajax_callback($form, $form_state) {
    $commands = array();
    $commands[] = ajax_command_replace('#race-check-con', drupal_render($form['field_fifth_constitution']));
    $commands[] = ajax_command_replace('#race-check-speed', drupal_render($form['field_fifth_speed']));
    $commands[] = ajax_command_replace('#race-check-features', drupal_render($form['field_fifth_racial_features']));
    $commands[] = ajax_command_replace('#race-check-conmod', drupal_render($form['field_fifth_constitution_modifie']));
    $commands[] = ajax_command_replace('#race-check-hit-dice', drupal_render($form['field_fifth_hit_dice']));
    return array('#type' => 'ajax', '#commands' => $commands);
}

function character_attributes_custom_ajax_callback2($form, $form_state) {
    $commands = array();
    $commands[] = ajax_command_replace('#subrace-check-wis', drupal_render($form['field_fifth_wisdom']));
    $commands[] = ajax_command_replace('#subrace-check-features', drupal_render($form['field_fifth_subracial_features']));
    $commands[] = ajax_command_replace('#subrace-check-hp', drupal_render($form['field_fifth_hit_points']));
    return array('#type' => 'ajax', '#commands' => $commands);
}
