<?php

function character_clean_form_alter(&$form, &$form_state, $form_id) {
    // find form id on target page
    // print_r($form_id);
    if ($form_id == 'character_node_form') {
        // print entire form so that you can find a specific value
        print '<pre>';
        print_r($form);
        print '</pre>';
        // $form['copy']['#type'] = 'hidden';
        // $form['subject']['#type'] = 'hidden';
        // $form['subject']['#default_value'] = 'Feedback';
    }
}