<?php
//renders menu item in navigation
function character_creator_menu(){
    $items = array();
    $items['character_creator'] = array (
        'title' => '5th Edition Character Creator',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('character_creator_main_branch_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['character_creator_two_novice_page'] = array (
        'title' => 'Second Page',
        'page callback' => 'character_creator_novice_two_form',
        // 'page arguments' => array('character_creator_novice_two_form'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['character_creator_two_advance_page'] = array (
        'title' => 'Second Page',
        'page callback' => 'drupal_get_form',
        // 'page arguments' => array('character_creator_advance_two_form'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

//function to render form
function character_creator_main_branch_form() {
    $active = array(0 => t('Take it easy...'), 1 => t('Lay it on me!'));
    $form['main_branch'] = array(
        '#title' => 'Customization Level',
        '#type' => 'radios',
        '#options' => $active,
        '#description' => t("How much customization do you want?"),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );
    return $form;
}

function character_creator_novice_two_form() {
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Novice Test',
    );
    return $form;
}

function character_creator_advance_two_form() {
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Advance Test',
    );
    return $form;
}

// //checks if form value is between 1 and 25
// function element_validate_range($element) {
//     if ($element['#value'] < 1 || $element['#value'] > 25) {
//         form_error($element, t('Value must be number between 1-25'));
//     }
// }
// //checks if form value is right or left
// function element_validate_alpha_range($element) {
//     if (!in_array($element['#value'], array('left', 'Left', 'LEFT', 'right', 'Right', 'RIGHT'))) {
//         form_error($element, t('Direction must be either left or right'));
//     }
// }
// //validation for entire form, returns error if it doesn't match regular expression
// function character_creator_form_validate($form, &$form_state) {
//     $pattern = '/[^A-Za-z0-9^\'^\:^\,^\-^\!^\(^\)^\.^\?^\"^\;\s]/';
//     $cipher_check = $form_state['values']['cipher_phrase'];
//     if (preg_match_all($pattern, $cipher_check)) {
//         form_set_error('cipher_phrase', 'Invalid character detected!');
//     }
// }
//runs when form is submitted
function character_creator_main_branch_submit($form, &$form_state) {
    $branch_switch = $form_state['values']['main_branch'];
    drupal_set_message(sprintf('<pre>%s</pre>', print_r($form_state['values']['main_branch'], TRUE)));
    if ($branch_switch == 0) {
        $form_state['redirect'] = 'character_creator_two_novice_page';
    } else {
        $form_state['redirect'] = 'character_creator_two_advance_page';
    }
}

function character_creator_two() {
    //prints session variable to screen
    return '<p>'.$_SESSION['character_creator_output'].'</p>';
}
